# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "method4"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "z_learner"
double_q: True
mixer: # Mixer becomes None
quantiles_num: 100
ucb: 60
ucb_w: 0.8
agent: "izrnn"
test_without_qtls: False

name: "method4"
